// Generated by lib/extract-jjs-game.mjs from Jujutsu Shenanigans' own
// Skill Builder tables (read in Roblox Studio, 2026-09-28): don't edit by hand,
// run `npm run game-data` with the game open in Studio.
//
//   NODE_DEFAULTS  SkillDefault.LineItems: each node kind's fields in the
//                  builder's order, with its type, default and tooltip. A
//                  field a node leaves out takes this default (null: unset).
//   PROP_DEFAULTS  SkillDefault.defaultProp: a skill's Properties.
//   STATES, ATTACK_TYPES, CHARACTERS, MOVES, SPECIALS: ListData's lists.
//   EFFECTS        BuilderFX: each VISUAL effect, the fields it reads, where
//                  it is placed from (see lib/extract-jjs-game.mjs).
//   ANIM_SETS      ListData.AnimList: ANIM_USE [set, n] is ANIM_SETS[set-1]
//                  .anims[n-1], as [path under ReplicatedStorage.Animations,
//                  animation ID].

export const NODE_DEFAULTS = {
 "AIM": [
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "AIR": [
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "ANIM": [
  {
   "key": "PREVIEW",
   "type": "pair",
   "code": 4,
   "def": [
    0,
    15
   ]
  },
  {
   "key": "ANIM_USE",
   "type": "str",
   "code": 3,
   "def": [
    1,
    1
   ]
  },
  {
   "key": "LOOPED",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Loop the animation as long as the skill is active."
  },
  {
   "key": "SPEED",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Multiplier of the Animation's speed."
  },
  {
   "key": "FADE IN",
   "type": "num",
   "code": 2,
   "def": 0.1,
   "desc": "How fast the Animation should fade in, in seconds."
  },
  {
   "key": "FADE OUT",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How fast the Animation should fade out, in seconds."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  }
 ],
 "BAR": [
  {
   "key": "AMOUNT",
   "type": "num",
   "code": 2,
   "def": 5
  },
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "BRANCH": [
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The BRANCH the user shall proceed to."
  },
  {
   "key": "RANDOM",
   "type": "str",
   "code": 8,
   "def": null,
   "desc": "Randomly selects a BRANCH to proceed to any time this NODE is activated. Branch names are separated by commas."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  }
 ],
 "CONNECT": [
  {
   "key": "SIGNAL",
   "type": "str",
   "code": 3,
   "def": "Nothing",
   "desc": "The block's signal."
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 0.1,
   "desc": "How long the signal should be active for, in seconds."
  },
  {
   "key": "RANGE",
   "type": "num",
   "code": 2,
   "def": 1e+38,
   "desc": "Activation range for the signal, in studs."
  }
 ],
 "COUNTER": [
  {
   "key": "ATTACK TYPE2",
   "type": "str",
   "code": 3,
   "def": "Melee"
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the counter is active for, in seconds."
  },
  {
   "key": "STUN",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the counter should stun the countered target for, in seconds. (-1 for no stun but still mark as LAST HIT)"
  },
  {
   "key": "CANCEL ENEMY",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Cancels the countered target."
  },
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Proceed to a BRANCH upon successfully countering a target."
  },
  {
   "key": "BRANCH TARGET",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Force the countered target to proceed to a BRANCH."
  },
  {
   "key": "REMOVE ON HIT",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "The counter gets removed upon activating."
  },
  {
   "key": "REFLECT",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Redirects all near projectiles"
  },
  {
   "key": "CONTINUE",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Removes the immunity for counters, meaning you will take damage when hit but the counter will still activate"
  }
 ],
 "DOMAIN": [
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "DUR": [
  {
   "key": "DURABILITY",
   "type": "num",
   "code": 2,
   "def": 1
  }
 ],
 "EVGIB": [
  {
   "key": "AMOUNT",
   "type": "num",
   "code": 2,
   "def": 5
  }
 ],
 "GRAB": [
  {
   "key": "BODY PART",
   "type": "str",
   "code": 3,
   "def": "HumanoidRootPart"
  },
  {
   "key": "BODY PART2",
   "type": "str",
   "code": 3,
   "def": "HumanoidRootPart"
  },
  {
   "key": "POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The TARGET LIMB's offset from LIMB. (X, Y, Z)"
  },
  {
   "key": "ROTATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The TARGET LIMB's rotation. (X, Y, Z)"
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the Grab should be active for."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  }
 ],
 "HITBOX": [
  {
   "key": "PREVIEW",
   "type": "pair",
   "code": 7,
   "def": [
    0,
    15
   ]
  },
  {
   "key": "POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 4",
   "desc": "The hitbox's position, the origin being the player's center. (X, Y, Z)"
  },
  {
   "key": "ROTATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The hitbox's rotation, relative to the player's orientation. (X, Y, Z)"
  },
  {
   "key": "SIZE",
   "type": "vec3",
   "code": 5,
   "def": "6, 6, 6",
   "desc": "The size of the hitbox. (X, Y, Z)"
  },
  {
   "key": "STUN",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the stun on hit should last for, in seconds. (-1 for no stun but still mark as LAST HIT)"
  },
  {
   "key": "STUN ANIM",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Plays a generic stun animation on the hit target."
  },
  {
   "key": "IGNORE WAKEUP",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Ignore the wakeup stun immunity (disable for accurate M1s)."
  },
  {
   "key": "DAMAGE",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How much damage should be dealt on hit."
  },
  {
   "key": "DEBREE",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "If not 0, causes destruction. The value determines the Debree Fidelity, which is 2 by default. Negative values don't spawn debree."
  },
  {
   "key": "ATTACK TYPE",
   "type": "str",
   "code": 3,
   "def": "Melee"
  },
  {
   "key": "BLOCKABLE",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "The hitbox is blockable from the front."
  },
  {
   "key": "360 BLOCK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The hitbox is blockable regardless of orientation."
  },
  {
   "key": "CANCEL ENEMY",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Cancels the hit target(s)."
  },
  {
   "key": "CLEAR KNOCKBACK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Clears hit target(s) velocity, also cancelling their ragdoll."
  },
  {
   "key": "CAN KILL",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "The hitbox can kill the hit target(s). If disabled, the target(s) cannot receive more damage than their current health."
  },
  {
   "key": "HIT RAGDOLL",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The hitbox can hit ragdolls."
  },
  {
   "key": "HIT USER",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The hitbox can hit the user of the skill."
  },
  {
   "key": "SINGLE TARGET",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "The hitbox can only hit one target."
  },
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Proceed to a BRANCH on hit."
  },
  {
   "key": "BRANCH TARGET",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Force the hit target(s) to proceed to a BRANCH."
  },
  {
   "key": "BRANCH FINISHER",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Proceed to a BRANCH if the hit was fatal."
  },
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of a projectile's tag. If matched with an existing projectile, the hitbox's origin is set to the projectile's position."
  },
  {
   "key": "LINK USER",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How long the hitbox is allowed to be hit, and transfers the attack to the user."
  }
 ],
 "HITCNCL": [
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Proceeds to BRANCH depending on the value of Flip."
  },
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "If set to FALSE: proceed to branch if a target WAS hit in the last (Time) seconds. <br />If set to TRUE: proceed to branch if a target WASN'T hit in the last (Time) seconds."
  },
  {
   "key": "ENDLAG",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Become stunned for (value) seconds on cancel."
  },
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The BRANCH the user shall proceed to."
  }
 ],
 "HOLD": [
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "HP": [
  {
   "key": "AMOUNT",
   "type": "num",
   "code": 2,
   "def": 10
  },
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "HPGIB": [
  {
   "key": "AMOUNT",
   "type": "num",
   "code": 2,
   "def": 5
  },
  {
   "key": "CAN KILL",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "JUMP": [
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "LOOK": [
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long it should be active for."
  },
  {
   "key": "SMOOTHNESS",
   "type": "num",
   "code": 2,
   "def": 40,
   "desc": "How fast should the constraint snap. (10 <-> 200)"
  },
  {
   "key": "HORIZONTAL ONLY",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Unlocks verticality on the constraint."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Target to look at, -1 to look at the cursor."
  },
  {
   "key": "RELATIVE FROM BRANCH",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Prioritizes the origin of branch instead of the LAST HIT target"
  },
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Prioritizes the projectile with this tag instead of the LAST HIT target."
  },
  {
   "key": "CAMERA DIRECTION",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Looks at the camera's direction instead of the LAST HIT target."
  },
  {
   "key": "GROUNDED",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Vertical direction affects character's vertical position."
  }
 ],
 "LOOP": [
  {
   "key": "LOOP BACK",
   "type": "num",
   "code": 2,
   "def": 1
  },
  {
   "key": "LOOP AMOUNT",
   "type": "num",
   "code": 2,
   "def": 3
  },
  {
   "key": "HOLD",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "PARTICLE": [
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of a projectile's tag. If matched with an existing projectile, the effect's origin (i.e. \"Limb\") is set to the projectile's position."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  },
  {
   "key": "PART SIZE",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "Keep at 0, 0, 0 to use attachments, otherwise makes a part with that size and spawns particles inside of it. (X, Y, Z)"
  },
  {
   "key": "TEXTURE",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "The effect's texture. Determined by an AssetID."
  },
  {
   "key": "EMIT COUNT",
   "type": "num",
   "code": 2,
   "def": 10,
   "desc": "Amount of particles to spawn at once. (DURATION MUST BE SET TO 0)"
  },
  {
   "key": "RATE",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "Particles per second. Only active if DURATION is > 0."
  },
  {
   "key": "DURATION",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "Seconds the emitter stays enabled. 0 = EMIT COUNT."
  },
  {
   "key": "COLOR",
   "type": "colorseq",
   "code": 10,
   "def": "255,255,255 0,0,0",
   "desc": "ColorSequence, colors separated by spaces. (r,g,b r,g,b r,g,b)"
  },
  {
   "key": "SIZE",
   "type": "seq",
   "code": 9,
   "def": "1, 0",
   "desc": "NumberSequence, values separated by commas (size1, size2, size3...)"
  },
  {
   "key": "BRIGHTNESS",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Particle brightness"
  },
  {
   "key": "TRANSPARENCY",
   "type": "seq",
   "code": 9,
   "def": "0, 1",
   "desc": "NumberSequence, same as SIZE"
  },
  {
   "key": "SQUASH",
   "type": "seq",
   "code": 9,
   "def": "0, 0",
   "desc": "NumberSequence, same as SIZE"
  },
  {
   "key": "LIFETIME",
   "type": "range",
   "code": 11,
   "def": "0.5, 1",
   "desc": "Particle lifetime in seconds. (min, max)"
  },
  {
   "key": "SPEED",
   "type": "range",
   "code": 11,
   "def": "5, 5",
   "desc": "Particle speed. (min, max)"
  },
  {
   "key": "ROTATION",
   "type": "range",
   "code": 11,
   "def": "0, 0",
   "desc": "Starting rotation of texture (min, max)"
  },
  {
   "key": "ROT SPEED",
   "type": "range",
   "code": 11,
   "def": "0, 0",
   "desc": "Rotation speed (min, max)"
  },
  {
   "key": "ACCELERATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "Acceleration of particle in world space. (X, Y, Z)"
  },
  {
   "key": "DRAG",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "Particle slowdown over time."
  },
  {
   "key": "LIGHT EMISSION",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How much the particle glows (0-1)."
  },
  {
   "key": "LIGHT INFLUENCE",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How much lighting affects the particle (0-1)."
  },
  {
   "key": "ZOFFSET",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "Depth offset from the camera."
  },
  {
   "key": "SPREAD ANGLE",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "Particle direction spread (X, Y, Z)"
  },
  {
   "key": "POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The effect's offset from the selected Limb. (X, Y, Z)"
  },
  {
   "key": "LOCK TO PART",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Particles move with the selected limb instead of staying in same place."
  },
  {
   "key": "BODY PART",
   "type": "str",
   "code": 3,
   "def": "HumanoidRootPart"
  },
  {
   "key": "ORIENTATION TYPE",
   "type": "str",
   "code": 3,
   "def": "FacingCamera"
  },
  {
   "key": "EMISSION DIRECTION",
   "type": "str",
   "code": 3,
   "def": "Top"
  },
  {
   "key": "FLIPBOOK SIZE",
   "type": "seq",
   "code": 9,
   "def": "0, 0",
   "desc": "Layout/size of the flipbook grid (0, 0 to disable)."
  },
  {
   "key": "FLIPBOOK MODE",
   "type": "str",
   "code": 3,
   "def": "OneShot"
  },
  {
   "key": "FLIPBOOK FRAMERATE",
   "type": "seq",
   "code": 9,
   "def": "10, 10",
   "desc": "Framerate of the flipbook, only applicable if FLIPBOOK MODE is set to Loop"
  },
  {
   "key": "SHAPE",
   "type": "str",
   "code": 3,
   "def": "Box"
  },
  {
   "key": "SHAPE INOUT",
   "type": "str",
   "code": 3,
   "def": "Outward"
  },
  {
   "key": "SHAPE PARTIAL",
   "type": "num",
   "code": 2,
   "def": 0
  },
  {
   "key": "RUN ON SERVER",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Runs the effect on server and for newly joined players as well (use for permanent auras, might cause performance issues on overuse)"
  },
  {
   "key": "CLIENT SIDED",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Runs the effect only for the target's client. (does not work with RUN ON SERVER)"
  },
  {
   "key": "CANCEL TAG",
   "type": "str",
   "code": 3,
   "def": null
  },
  {
   "key": "CANCEL",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Cancel all emitters with same tag."
  },
  {
   "key": "CANCEL ON INTERRUPT",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Cancel all emitters with same tag on interruption."
  }
 ],
 "PROJECTILE": [
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of the tag. Used by VISUAL, HITBOX and SOUND nodes as a link to the projectile."
  },
  {
   "key": "CANCEL PROJECTILE",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Removes all projectiles with same PROJECTILE TAG, if CACHE is enabled it won't remove the cached projectile."
  },
  {
   "key": "ID CHECK",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Makes the projectile tag only work in this move, if disabled all projectiles spawned with same tag will be seen."
  },
  {
   "key": "SPAWN AT PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Spawns the projectile relative to an already existing projectile with this tag."
  },
  {
   "key": "POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The projectile's starting position, the origin being the player's center. (X, Y, Z)"
  },
  {
   "key": "ROTATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The projectile's rotation, relative to the player's orientation. (X, Y, Z)"
  },
  {
   "key": "SIZE",
   "type": "vec3",
   "code": 5,
   "def": "6, 6, 6",
   "desc": "The size of the projectile. (X, Y, Z)"
  },
  {
   "key": "SPEED",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How fast the projectile should travel, in studs per second."
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1
  },
  {
   "key": "STUN",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the stun on hit should last for, in seconds. (-1 for no stun but still mark as LAST HIT)"
  },
  {
   "key": "STUN ANIM",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Plays a generic stun animation on the hit target."
  },
  {
   "key": "IGNORE WAKEUP",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Ignore the wakeup stun immunity (disable for accurate M1s)."
  },
  {
   "key": "DAMAGE",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How much damage should be dealt on hit."
  },
  {
   "key": "DEBREE",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "If not 0, causes destruction. The value determines the Debree Fidelity, which is 2 by default. Negative values don't spawn debree."
  },
  {
   "key": "ATTACK TYPE",
   "type": "str",
   "code": 3,
   "def": "Melee"
  },
  {
   "key": "BLOCKABLE",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "The projectile is blockable from the front."
  },
  {
   "key": "360 BLOCK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The projectile is blockable regardless of orientation."
  },
  {
   "key": "CANCEL ENEMY",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Cancels the hit target(s)."
  },
  {
   "key": "CLEAR KNOCKBACK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Clears hit target(s) velocity, also cancelling their ragdoll."
  },
  {
   "key": "CAN KILL",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "The hitbox can kill the hit target(s). If disabled, the target(s) cannot receive more damage than their current health, instead leaving them at the lowest possible amount, if the hit was fatal."
  },
  {
   "key": "HIT RAGDOLL",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The hitbox can hit ragdolls."
  },
  {
   "key": "HIT USER",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The hitbox can hit the user of the skill."
  },
  {
   "key": "AIM LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "The projectile's rotation gets aligned towards the position of the LAST HIT target. (LAST HIT: target hit in the last (value) seconds.)"
  },
  {
   "key": "CONTINUE",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The projectile continues travelling after hitting a target, or colliding with the environment."
  },
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Proceed to a BRANCH on hit."
  },
  {
   "key": "BRANCH TARGET",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Force the hit target(s) to proceed to a BRANCH."
  },
  {
   "key": "BRANCH COLLIDED",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Proceed to a BRANCH if the projectile collided with the environment. If empty, the projectile ignores collisions"
  },
  {
   "key": "FILTER INTERVAL",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "The projectile, upon hitting a target, waits (value) seconds before it can hit the same target."
  },
  {
   "key": "REFLECT COUNT",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How many times the projectile can bounce off the environment before despawning."
  },
  {
   "key": "CACHE",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Stores projectile in the cache on hit, making PROJECTILE tag usable even after it's gone."
  }
 ],
 "SETCD": [
  {
   "key": "KEY",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "The move to set cooldown for. (-1 for current move)"
  },
  {
   "key": "COOLDOWN",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "The cooldown itself. (-1 for default cooldown)"
  }
 ],
 "SETMELEE": [
  {
   "key": "COMBO",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "What part of the melee combo you are set to. Set this to -1 to keep last used melee combo."
  },
  {
   "key": "OFFSET",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How long before the melee resets back to 0."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  }
 ],
 "SFX": [
  {
   "key": "ID",
   "type": "num",
   "code": 2,
   "def": 12222253,
   "desc": "The sound's AssetID."
  },
  {
   "key": "SPEED",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Multiplier of the Sound's playback speed."
  },
  {
   "key": "VOLUME",
   "type": "num",
   "code": 2,
   "def": 0.5,
   "desc": "Multiplier of the Sound's volume."
  },
  {
   "key": "START",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "Where to begin the Sound from, starting at 0 seconds."
  },
  {
   "key": "END",
   "type": "num",
   "code": 2,
   "def": 500,
   "desc": "Where to end the Sound at, in seconds."
  },
  {
   "key": "FADE IN",
   "type": "num",
   "code": 2,
   "def": 0
  },
  {
   "key": "FADE OUT",
   "type": "num",
   "code": 2,
   "def": 0
  },
  {
   "key": "CANCEL",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Cancels all currently playing Sound NODEs."
  },
  {
   "key": "GLOBAL",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Disables 3D falloff, playing the sound at the same volume for everyone."
  },
  {
   "key": "CLIENT SIDED",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Runs the sound only for the target's client."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  },
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of a projectile's tag. If matched with an existing projectile, the sound follows the projectile."
  }
 ],
 "SKILL": [
  {
   "key": "MOVE",
   "type": "str",
   "code": 3,
   "def": "Divergent Fist"
  },
  {
   "key": "SPEED",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Multiplier of the Skill's speed."
  },
  {
   "key": "CANCEL LAST",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Cancels the previous NODE if set to true."
  },
  {
   "key": "ENABLE VARIANTS",
   "type": "bool",
   "code": 1,
   "def": true
  },
  {
   "key": "HOLD FOR",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How many seconds to hold the Skill for. Only applicable to holdable Skills, such as Max Elephant."
  },
  {
   "key": "START",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "Where to begin the Skill from, starting at 0 seconds."
  }
 ],
 "SPECIAL": [
  {
   "key": "SPEC",
   "type": "str",
   "code": 3,
   "def": "Limitless"
  },
  {
   "key": "SPEED",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Multiplier of the Skill's speed."
  },
  {
   "key": "CANCEL LAST",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Cancels the previous NODE if set to true."
  },
  {
   "key": "ENABLE VARIANTS",
   "type": "bool",
   "code": 1,
   "def": true
  }
 ],
 "STATE": [
  {
   "key": "STATE",
   "type": "str",
   "code": 3,
   "def": "Stun"
  },
  {
   "key": "VALUE",
   "type": "str",
   "code": 3,
   "def": 1,
   "desc": "Used for SpeedMultiplier, JumpMultiplier, and Scale."
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the State should be active for."
  },
  {
   "key": "CANCEL ON END",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The State gets cancelled when the skill ends."
  },
  {
   "key": "DISABLE BURST",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Burst is disabled while the State is active."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last X seconds."
  },
  {
   "key": "CHECK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Checks if LAST HIT has that state"
  },
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Only applicable if Check is true. <br />The BRANCH that shall be proceeded to if Check successfully completes the state check, then proceed to BRANCH.)"
  },
  {
   "key": "STATE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of the tag. Used by other STATE nodes to Cancel the state, if the selected State is \"Cancel\""
  }
 ],
 "TAG": [
  {
   "key": "TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of the tag. This name can be used as a variable by all TAG nodes."
  },
  {
   "key": "VALUE",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Value of the tag. Can be a number, or a string of text."
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the tag should be active for, if changed."
  },
  {
   "key": "CHECK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Checks if the tag's value matches (value). Performing \"less than\" and \"greater than\" operations can be done by prefixing the value with < or > (e.g. <1 for \"less than 1\")."
  },
  {
   "key": "ADD/REMOVE",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Only applicable if Set is false. <br />If true, adds +(value) to the tag's value. If false, subtracts."
  },
  {
   "key": "SET",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Replaces the tag's value with (value)."
  },
  {
   "key": "BRANCH",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Only applicable if Check is true. <br />The BRANCH that shall be proceeded to if Check successfully completes the comparison operation (e.g. if the tag's value is equal to (value), then proceed to BRANCH.)"
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last X seconds."
  }
 ],
 "TELEPORT": [
  {
   "key": "POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "Character's offset from last hit. (X, Y, Z)"
  },
  {
   "key": "ROTATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "Character's rotation at the location. (X, Y, Z)"
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Applies POSITION and ROTATION of the LAST HIT target"
  },
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "Prioritizes the projectile with this tag instead of the LAST HIT target."
  },
  {
   "key": "RELATIVE FROM BRANCH",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Prioritizes the origin of branch instead of the LAST HIT target"
  },
  {
   "key": "IGNORE WALLS",
   "type": "bool",
   "code": 1,
   "def": true,
   "desc": "Teleport ignores any obstacles on it's way"
  }
 ],
 "ULT": [
  {
   "key": "FLIP",
   "type": "bool",
   "code": 1,
   "def": false
  }
 ],
 "ULTGIB": [
  {
   "key": "AMOUNT",
   "type": "num",
   "code": 2,
   "def": 5
  }
 ],
 "VELO": [
  {
   "key": "FORCE",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The direction where force should be applied towards. Higher values = bigger force (X, Y, Z)"
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "How long the force should be active for."
  },
  {
   "key": "FADE",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "The force linearly fades to 0,0,0 over time."
  },
  {
   "key": "TRACK",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Force direction tracks the torso's orientation during the entire duration of the NODE."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  },
  {
   "key": "RAGDOLL",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "If the value is above 0, ragdolls for (value) seconds."
  },
  {
   "key": "TRUE RAGDOLL",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Disables ragdoll cancel."
  },
  {
   "key": "RELATIVE FROM BRANCH",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Force direction is relative to the Branch origin."
  }
 ],
 "VISUAL": [
  {
   "key": "EFFECT",
   "type": "str",
   "code": 3,
   "def": "Slash"
  },
  {
   "key": "AMOUNT",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How many Effects to emit. If the selected Effect is \"Mesh\", the value of this property becomes the Mesh ID."
  },
  {
   "key": "TEXTURE",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "The effect's texture. Determined by an AssetID."
  },
  {
   "key": "COLOR",
   "type": "color",
   "code": 6,
   "def": "255, 255, 255",
   "desc": "The effect's color. (R, G, B)"
  },
  {
   "key": "ALT COLOR",
   "type": "color",
   "code": 6,
   "def": "255, 255, 255",
   "desc": "The color to fade into over the course of the Effect's duration."
  },
  {
   "key": "OPACITY",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "The effect's transparency, with 0 being fully opaque and 1 being completely invisible."
  },
  {
   "key": "ALT OPACITY",
   "type": "num",
   "code": 2,
   "def": 0,
   "desc": "The transparency to fade into."
  },
  {
   "key": "POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The effect's offset from the selected Limb. (X, Y, Z)"
  },
  {
   "key": "ALT POSITION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The offset to fade into."
  },
  {
   "key": "ROTATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The effect's rotation. (X, Y, Z)"
  },
  {
   "key": "ALT ROTATION",
   "type": "vec3",
   "code": 5,
   "def": "0, 0, 0",
   "desc": "The rotation to fade into."
  },
  {
   "key": "SIZE",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "Multiplier of the effect's size."
  },
  {
   "key": "ALT SIZE",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "The size to fade into."
  },
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "How long the Effect should be active for. Alt (Property) use Time as the speed."
  },
  {
   "key": "LAST HIT",
   "type": "num",
   "code": 2,
   "def": -1,
   "desc": "Activates this NODE on a target hit in the last (value) seconds."
  },
  {
   "key": "BODY PART",
   "type": "str",
   "code": 3,
   "def": "HumanoidRootPart"
  },
  {
   "key": "VISUAL TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of the tag. Used by other VISUAL nodes to Cancel the effect, if the selected Effect is \"Cancel\""
  },
  {
   "key": "PROJECTILE TAG",
   "type": "str",
   "code": 3,
   "def": null,
   "desc": "The name of a projectile's tag. If matched with an existing projectile, the effect's origin (i.e. \"Limb\") is set to the projectile's position."
  },
  {
   "key": "RUN ON SERVER",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Runs the effect serverside, recommended for weapons and such."
  },
  {
   "key": "CLIENT SIDED",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Runs the effect only for the target's client."
  },
  {
   "key": "CANCEL ON INTERRUPT",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Cancels the effect when the skill is interrupted. Requires VISUAL TAG."
  },
  {
   "key": "RELATIVE FROM BRANCH",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Body part is selected from the Branch origin."
  },
  {
   "key": "CAN COLLIDE",
   "type": "bool",
   "code": 1,
   "def": false,
   "desc": "Enables collision on the effect, making it tangible."
  },
  {
   "key": "EASING STYLE",
   "type": "str",
   "code": 3,
   "def": "Linear"
  },
  {
   "key": "EASING DIRECTION",
   "type": "str",
   "code": 3,
   "def": "In"
  },
  {
   "key": "SIZE 2",
   "type": "vec3",
   "code": 5,
   "def": "-1, -1, -1",
   "desc": "Uniform sizing, only works for mesh and part related effects. Change to a positive vector to utilize. (X, Y, Z)"
  },
  {
   "key": "ALT SIZE 2",
   "type": "vec3",
   "code": 5,
   "def": "-1, -1, -1",
   "desc": "Uniform sizing, only works for mesh and part related effects. Change to a positive vector to utilize. (X, Y, Z)"
  }
 ],
 "WAIT": [
  {
   "key": "TIME",
   "type": "num",
   "code": 2,
   "def": 1,
   "desc": "(number) How many seconds to delay the next NODE by."
  }
 ]
};

export const PROP_DEFAULTS = {
 "USE": false,
 "REP2": false,
 "NOSTUN": false,
 "AWK2": false,
 "KNOCK": 1,
 "KEEP": false,
 "REP": false,
 "VAR": "-",
 "DMG": 1,
 "NOCANCEL": false,
 "USEONDEATH": false,
 "AWK": false,
 "INV": false
};

export const STATES = [
 "Cancel",
 "Stun",
 "IFrame",
 "NoM1",
 "NoSprint",
 "NoJump",
 "NoDash",
 "NoBlock",
 "NoParkour",
 "NoMass",
 "NoDeath",
 "DisableChase",
 "Block",
 "DirectionLock",
 "SpeedMultiplier",
 "JumpMultiplier",
 "DamageMultiplier",
 "HealthMultiplier",
 "KnockbackMultiplier",
 "Scale",
 "InSkill",
 "CameraMaxZoomDistance",
 "Wakeup",
 "Ragdoll",
 "Character",
 "Projection",
 "Bleed",
 "LastHit"
];

export const ATTACK_TYPES = [
 "Melee",
 "Bullet",
 "Explosion",
 "Swarm",
 "Domain"
];

export const CHARACTERS = [
 "Gojo",
 "Itadori",
 "Hakari",
 "Megumi",
 "Mahoraga",
 "Mahito",
 "Choso",
 "Todo",
 "Locust",
 "Hiromi",
 "Yuki",
 "Heian",
 "Yuta",
 "Charles",
 "Mechamaru",
 "Naoya",
 "Nanami",
 "Goku",
 "Haruta",
 "MeiMei",
 "Hanami",
 "Ryu",
 "Kurourushi",
 "Reggie",
 "Uro"
];

export const MOVES = [
 {
  "color": [
   170,
   255,
   255
  ],
  "name": "HONORED ONE",
  "moves": [
   "Lapse Blue",
   "Reversal Red",
   "Rapid Punches",
   "Twofold Kick",
   "Lapse Blue MAX",
   "Reversal Red MAX",
   "Hollow Purple",
   "Infinite Void"
  ]
 },
 {
  "color": [
   255,
   155,
   155
  ],
  "name": "VESSEL",
  "moves": [
   "Cursed Strikes",
   "Crushing Blow",
   "Divergent Fist",
   "Manji Kick",
   "Dismantle",
   "Open",
   "Rush",
   "Malevolent Shrine"
  ]
 },
 {
  "color": [
   170,
   255,
   127
  ],
  "name": "RESTLESS GAMBLER",
  "moves": [
   "Reserve Balls",
   "Shutter Doors",
   "Rough Energy",
   "Fever Breaker",
   "Lucky Volley",
   "Lucky Rushdown",
   "Overwhelming Luck",
   "Energy Surge"
  ]
 },
 {
  "color": [
   120,
   120,
   120
  ],
  "name": "TEN SHADOWS",
  "moves": [
   "Rabbit Escape",
   "Nue",
   "Toad",
   "Divine Dog: Totality",
   "Max Elephant",
   "Great Serpent",
   "Shadow Swarm",
   "Mahoraga"
  ]
 },
 {
  "color": [
   255,
   255,
   255
  ],
  "name": "MAHORAGA",
  "moves": [
   "Divine Pummel",
   "Ground Pitch",
   "Earthquake",
   "Takedown",
   "Adaptation",
   "World Slash"
  ]
 },
 {
  "color": [
   255,
   170,
   255
  ],
  "name": "PERFECTION",
  "moves": [
   "Stockpile",
   "Soul Fire",
   "Focus Strike",
   "Body Repel",
   "Idle Transfiguration",
   "Body Disfigure",
   "Spike Wrath",
   "Embodiment of Self Perfection",
   "Widespread Strikes",
   "Face Blitz",
   "Crushing Rushdown",
   "Head Splitter"
  ]
 },
 {
  "color": [
   170,
   75,
   75
  ],
  "name": "BLOOD MANIPULATOR",
  "moves": [
   "Piercing Blood",
   "Flowing Red Scale",
   "Supernova",
   "Blood Edge",
   "Slicing Exorcism",
   "Wing King",
   "Blood Rain",
   "Plasma Wave"
  ]
 },
 {
  "color": [
   170,
   255,
   255
  ],
  "name": "SWITCHER",
  "moves": [
   "Swift Kick",
   "Brute Force",
   "Pebble Throw",
   "Elbow Drop",
   "Idol's Debut",
   "Climax Jumping",
   "Dreams",
   "Brothers"
  ]
 },
 {
  "color": [
   170,
   255,
   127
  ],
  "name": "LOCUST",
  "moves": [
   "Crushing Jaws",
   "Clever",
   "Wing Throw",
   "Black Mucus"
  ]
 },
 {
  "color": [
   115,
   99,
   77
  ],
  "name": "DEFENSE ATTORNEY",
  "moves": [
   "Extended Swings",
   "Justice Served",
   "Judgement's Reach",
   "Pressing Charges",
   "Execution",
   "Final Judgement",
   "Verdict",
   "Triple Sentence",
   "Grapple"
  ]
 },
 {
  "color": [
   170,
   170,
   255
  ],
  "name": "STAR RAGE",
  "moves": [
   "Garuda Rebound",
   "Rising Rage",
   "Mass Breaker",
   "Garuda Stab"
  ]
 },
 {
  "color": [
   255,
   85,
   0
  ],
  "name": "HEIAN",
  "moves": [
   "Strong Dismantle",
   "Open FURNACE",
   "Cleave Rush",
   "Kamutoke"
  ]
 },
 {
  "color": [
   255,
   170,
   255
  ],
  "name": "CURSED PARTNERS",
  "moves": [
   "Severing Path",
   "Resolute Slash",
   "Veilstep",
   "Second Wind",
   "Outburst",
   "Revolve",
   "Rika Downslam",
   "Rika Launch",
   "Rika Slam",
   "Rika Haymaker",
   "Rika Grab",
   "Rika Throw",
   "Rika Smash",
   "True Love Beam",
   "Authentic Mutual Love",
   "Elbow Rush",
   "Copy",
   "Energy Ripple"
  ]
 },
 {
  "color": [
   255,
   235,
   235
  ],
  "name": "ASPIRING MANGAKA",
  "moves": [
   "Despair",
   "Shut Up!",
   "Eye Catching",
   "Sacrilege"
  ]
 },
 {
  "color": [
   225,
   10,
   75
  ],
  "name": "PUPPET MASTER",
  "moves": [
   "Ultra Spin",
   "Boost On",
   "Ultra Cannon",
   "Heat Emission",
   "Miracle Cannon",
   "Pigeon Viola",
   "Absolute Destruction",
   "Technique Charge",
   "Boost On OLD",
   "Ultra Cannon OLD"
  ]
 },
 {
  "color": [
   128,
   126,
   255
  ],
  "name": "HEAD OF THE HEI",
  "moves": [
   "Projection Breaker",
   "Bleedout",
   "Decisive Strike",
   "Cursory Impact",
   "Top Speed",
   "Flash Freezing",
   "Tendril Grab",
   "Time Cell Moon Palace",
   "Decisive Strike OLD"
  ]
 },
 {
  "color": [
   94,
   191,
   255
  ],
  "name": "SALARYMAN",
  "moves": [
   "Cleaving Whirlwind",
   "Severance Kick",
   "Blunt Cut",
   "Stabilize",
   "Ratio Breaker",
   "Sharpen",
   "Interrogate",
   "Collapse"
  ]
 },
 {
  "color": [
   255,
   21,
   52
  ],
  "name": "MONKEY KID",
  "moves": [
   "Kamehameha",
   "Ki Spam",
   "Staff Extend",
   "Staff Uppercut"
  ]
 },
 {
  "color": [
   167,
   125,
   203
  ],
  "name": "LUCKY COWARD",
  "moves": [
   "Ambush",
   "Backstab",
   "Trip",
   "Cheap Shot",
   "Ankle Cutter",
   "High Time",
   "Dirty Play"
  ]
 },
 {
  "color": [
   35,
   40,
   80
  ],
  "name": "CROW CHARMER",
  "moves": [
   "Impetus Updraft",
   "Circling",
   "Gliding Flight",
   "Bird Control"
  ]
 },
 {
  "color": [
   172,
   203,
   163
  ],
  "name": "DISASTER PLANTS",
  "moves": [
   "Root Swarm",
   "Surging Thorns",
   "Bud Shot",
   "Defense Response",
   "Cursed Buds",
   "Shining Sea of Growing Branches",
   "Flower Field",
   "Root Rampage"
  ]
 },
 {
  "color": [
   170,
   255,
   255
  ],
  "name": "TRUE CANNON",
  "moves": [
   "Granite Blast",
   "Unsatisfied",
   "Second Helping",
   "Appetizer",
   "\"What are you after?\"",
   "\"I had no idea...\"",
   "\"This is what dessert is like!\"",
   "\"You weren't invited.\""
  ]
 },
 {
  "color": [
   101,
   35,
   44
  ],
  "name": "BLACK DEATH",
  "moves": [
   "Festering Strikes",
   "Detach",
   "Chokehold",
   "Roach Swarm"
  ]
 },
 {
  "color": [
   255,
   255,
   255
  ],
  "name": "REGISTER",
  "moves": [
   "Gushing Wound",
   "Homerun",
   "Littering",
   "Coupon",
   "Piano Drop",
   "Garage Sale",
   "Blunt Trauma",
   "Fleche",
   "Drone Strike",
   "Pole Vault"
  ]
 },
 {
  "color": [
   255,
   165,
   165
  ],
  "name": "SKY ASSASSIN",
  "moves": [
   "Blind Rage",
   "Sky Distortion",
   "Thin Ice Breaker"
  ]
 }
];

export const SPECIALS = {
 "Limitless": 1,
 "Cleave": 2,
 "Combat Instincts": 2,
 "Door Guard": 3,
 "Rhythm": 3,
 "Lurking Shadow": 4,
 "Adaptation Wheel": 5,
 "Self Transfiguration": 6,
 "Convergence": 7,
 "Boogie Woogie": 8,
 "Fluttering Pounce": 9,
 "Domain Amplification": 10,
 "No Escape": 10,
 "Mass Buildup": 11,
 "Incantation": 12,
 "Rika": 13,
 "Clairvoyance": 14,
 "Energy Output": 15,
 "Offload": 15,
 "Acceleration": 16,
 "Projection Sorcery": 16,
 "Ratio Point": 17,
 "Instant Transmission": 18,
 "Helping Hand": 19,
 "Flock": 20,
 "Flower Field": 21,
 "Restyle": 22,
 "Earthen Insect Trance": 23,
 "Discard": 24
};

export const EFFECTS = {
 "360 Wind": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Hakari.RoughHit.Wind"
 },
 "Afterimage": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "SIZE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Damage.HitGlow"
 },
 "Afterimage2": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "SIZE",
   "TIME"
  ],
  "origin": "none"
 },
 "Beam": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.BuilderFX.Beam"
 },
 "Beams": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Hakari.RoughHit.Wind2"
 },
 "Billboard": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT SIZE",
   "AMOUNT",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "SIZE",
   "TEXTURE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Gojo.Dialogue"
 },
 "Black Flash": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.DivergentFist.BlackFlashHit"
 },
 "Block": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "ALT SIZE 2",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "SIZE 2",
   "TIME"
  ],
  "origin": "effect",
  "template": "Utils.BuilderFX.Ball"
 },
 "Blood": {
  "fields": [
   "AMOUNT",
   "BODY PART",
   "SIZE"
  ],
  "origin": "none"
 },
 "Burst": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.DashCancel"
 },
 "Camera": {
  "fields": [
   "ALT POSITION",
   "ALT ROTATION",
   "BODY PART",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "none",
  "screen": true
 },
 "Cancel": {
  "fields": [
   "BODY PART",
   "VISUAL TAG"
  ],
  "origin": "none"
 },
 "Circle Glow": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Hakari.RoughHit.Glow"
 },
 "Clash": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Misc.Items.Clash.Attachment"
 },
 "Cleave": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.MalevolantShrine.Hit"
 },
 "Cursed Energy": {
  "fields": [
   "ALT OPACITY",
   "BODY PART",
   "COLOR",
   "OPACITY",
   "POSITION",
   "SIZE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Itadori.DivergentFist.DivergentFist"
 },
 "Cylinder": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "ALT SIZE 2",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "SIZE 2",
   "TIME"
  ],
  "origin": "effect",
  "template": "Utils.BuilderFX.Cylinder"
 },
 "Dismantle": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT ROTATION",
   "BODY PART",
   "COLOR",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.Dismantle.DismantleFly"
 },
 "Distortion": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.BuilderFX.Distortion"
 },
 "Energy Sparks": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Hakari.RoughHit.Sparks"
 },
 "Field of View": {
  "fields": [
   "AMOUNT",
   "EASING DIRECTION",
   "EASING STYLE",
   "TIME"
  ],
  "origin": "none",
  "screen": true
 },
 "Flames": {
  "fields": [
   "ALT OPACITY",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "OPACITY",
   "SIZE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Damage.Flames"
 },
 "Glow": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Damage.HitGlow"
 },
 "Light": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part"
 },
 "Mass Hit": {
  "fields": [
   "ALT OPACITY",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "OPACITY",
   "POSITION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Yuki.MassHit"
 },
 "Melee Trail": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Damage.CombatTrail"
 },
 "Mesh": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "ALT SIZE 2",
   "AMOUNT",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "SIZE 2",
   "TEXTURE",
   "TIME"
  ],
  "origin": "effect",
  "template": "Utils.BuilderFX.Ball"
 },
 "Overlay": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT SIZE",
   "COLOR",
   "OPACITY",
   "SIZE",
   "TEXTURE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Todo.Woah",
  "screen": true
 },
 "Ring": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.CounterHit.Feint.Ring"
 },
 "Rough Energy": {
  "fields": [
   "ALT OPACITY",
   "BODY PART",
   "COLOR",
   "OPACITY",
   "POSITION",
   "SIZE",
   "TIME"
  ],
  "origin": "none",
  "template": "Utils.Hakari.RoughEnergy"
 },
 "Screen Color": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT SIZE",
   "AMOUNT",
   "COLOR",
   "OPACITY",
   "SIZE",
   "TIME"
  ],
  "origin": "none",
  "screen": true
 },
 "Shake Heavy": {
  "fields": [
   "AMOUNT"
  ],
  "origin": "none",
  "screen": true
 },
 "Shake Light": {
  "fields": [
   "AMOUNT"
  ],
  "origin": "none",
  "screen": true
 },
 "Shake Medium": {
  "fields": [
   "AMOUNT"
  ],
  "origin": "none",
  "screen": true
 },
 "Shine": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Megumi.Mahoraga.Cursed.Shine"
 },
 "Slash": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "weld",
  "template": "Utils.BuilderFX.Slash"
 },
 "Sparks": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.CounterHit.Feint.Sparks"
 },
 "Sphere": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "ALT SIZE 2",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "SIZE 2",
   "TIME"
  ],
  "origin": "effect",
  "template": "Utils.BuilderFX.Ball"
 },
 "Star": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.CounterHit.Feint.Star"
 },
 "Star Outline": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Hakari.Indicators.BallFire.Ring"
 },
 "Visibility": {
  "fields": [
   "ALT OPACITY",
   "BODY PART",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "TIME"
  ],
  "origin": "none"
 },
 "Weak Lightning": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Megumi.NueShock"
 },
 "Wedge": {
  "fields": [
   "ALT COLOR",
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "ALT SIZE",
   "ALT SIZE 2",
   "BODY PART",
   "CAN COLLIDE",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "SIZE 2",
   "TIME"
  ],
  "origin": "effect",
  "template": "Utils.BuilderFX.Ball"
 },
 "Whirl Slash": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "SIZE",
   "TIME"
  ],
  "origin": "weld",
  "template": "Utils.BuilderFX.SlashWhirl"
 },
 "Wind Expand": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Megumi.Mahoraga.RitualStart.Attachment"
 },
 "Wind Ring": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Hakari.Indicators.BallFire.Wind"
 },
 "Wind Streak": {
  "fields": [
   "ALT OPACITY",
   "ALT POSITION",
   "ALT ROTATION",
   "AMOUNT",
   "BODY PART",
   "COLOR",
   "EASING DIRECTION",
   "EASING STYLE",
   "OPACITY",
   "POSITION",
   "ROTATION",
   "TIME"
  ],
  "origin": "part",
  "template": "Utils.Itadori.RushWind.Dash1"
 }
};

export const ANIM_SETS = [
 {
  "character": "Gojo",
  "anims": [
   [
    "Gojo.HollowPurple",
    "132748613906344"
   ],
   [
    "Gojo.InfiniteVoid",
    "132725601768618"
   ],
   [
    "Gojo.LapseBlue",
    "137865634124104"
   ],
   [
    "Gojo.LapseBlueMaximum",
    "101162958113766"
   ],
   [
    "Gojo.RapidPunches",
    "95421145178968"
   ],
   [
    "Gojo.ReversalRed",
    "137654778575373"
   ],
   [
    "Gojo.ReversalRedMaximum",
    "124937162378188"
   ],
   [
    "Gojo.Teleport",
    "99920923658527"
   ],
   [
    "Gojo.TwofoldHit",
    "132673356426065"
   ],
   [
    "Gojo.TwofoldKick",
    "104749346956269"
   ],
   [
    "Gojo.Ultimate",
    "84716311536982"
   ],
   [
    "Gojo.ShortVoid",
    "116811846715462"
   ],
   [
    "Gojo.Melee.Melee1",
    "127851700400958"
   ],
   [
    "Gojo.Melee.Melee2",
    "72548435296350"
   ],
   [
    "Gojo.Melee.Melee3",
    "84547415708554"
   ],
   [
    "Gojo.Melee.Melee4",
    "127851700400958"
   ],
   [
    "Gojo.Melee.Up",
    "134243365075812"
   ],
   [
    "Gojo.Melee.Down",
    "92966188946988"
   ],
   [
    "Gojo.Melee.Chase",
    "110978068388232"
   ]
  ]
 },
 {
  "character": "Itadori",
  "anims": [
   [
    "Itadori.CursedStrike",
    "77200218033775"
   ],
   [
    "Itadori.CursedStrikeHit",
    "127402740019290"
   ],
   [
    "Itadori.CrushingBlow",
    "124901309160375"
   ],
   [
    "Itadori.Variants.DivergentFist1",
    "100962226150441"
   ],
   [
    "Itadori.Variants.DivergentFist2",
    "95852624447551"
   ],
   [
    "Itadori.Variants.DivergentFist3",
    "74145636023952"
   ],
   [
    "Itadori.Variants.DivergentFist4",
    "123171106092050"
   ],
   [
    "Itadori.ManjiKick",
    "82987093810211"
   ],
   [
    "Itadori.ManjiKickHit",
    "100131148300498"
   ],
   [
    "Itadori.Cleave",
    "111593784328268"
   ],
   [
    "Itadori.Dismantle",
    "131506102901134"
   ],
   [
    "Itadori.FlameArrow",
    "137611726964398"
   ],
   [
    "Itadori.Rush",
    "107554693613496"
   ],
   [
    "Itadori.RushHit",
    "125129631010293"
   ],
   [
    "Itadori.MalevolentShrine",
    "121984128639453"
   ],
   [
    "Itadori.SlaughterDemon",
    "121923107958102"
   ],
   [
    "Itadori.Ultimate",
    "112577421904593"
   ],
   [
    "Itadori.UltimateEnchain",
    "81633998750531"
   ],
   [
    "Itadori.Instincts",
    "130206074036010"
   ],
   [
    "Itadori.Melee.Melee1",
    "95295463826732"
   ],
   [
    "Itadori.Melee.Melee2",
    "105077924973072"
   ],
   [
    "Itadori.Melee.Melee3",
    "124862357369335"
   ],
   [
    "Itadori.Melee.Melee4",
    "81630213087988"
   ]
  ]
 },
 {
  "character": "Hakari",
  "anims": [
   [
    "Hakari.Counter",
    "92529934565092"
   ],
   [
    "Hakari.EnergySurge",
    "91984445049000"
   ],
   [
    "Hakari.FeverBreaker",
    "108123475959041"
   ],
   [
    "Hakari.IdleDeath",
    "118861398234801"
   ],
   [
    "Hakari.LuckyRushdown",
    "132281807148575"
   ],
   [
    "Hakari.LuckyVolley",
    "95901746347992"
   ],
   [
    "Hakari.OverLuck",
    "120480195428173"
   ],
   [
    "Hakari.ReserveBalls",
    "82541714192027"
   ],
   [
    "Hakari.Rhythm",
    "136948942223547"
   ],
   [
    "Hakari.RoughEnergy",
    "72467492674240"
   ],
   [
    "Hakari.ShutterDoors",
    "72063002791216"
   ],
   [
    "Hakari.Melee.Melee1",
    "94588892125071"
   ],
   [
    "Hakari.Melee.Melee2",
    "97868312130612"
   ],
   [
    "Hakari.Melee.Melee3",
    "140588454098230"
   ],
   [
    "Hakari.Melee.Melee4",
    "138826758216894"
   ],
   [
    "Hakari.Melee.Up",
    "109299799610861"
   ],
   [
    "Hakari.Melee.Chase",
    "99451940496871"
   ]
  ]
 },
 {
  "character": "Megumi",
  "anims": [
   [
    "Megumi.DivineDog",
    "81112033595734"
   ],
   [
    "Megumi.GreatSerpent",
    "75390215999547"
   ],
   [
    "Megumi.MahoragaSummon",
    "110184037389280"
   ],
   [
    "Megumi.MahoragaUse",
    "127843796051633"
   ],
   [
    "Megumi.MaxElephant",
    "131219281339199"
   ],
   [
    "Megumi.Nue",
    "111077341852080"
   ],
   [
    "Megumi.RabbitEscape",
    "132653290201368"
   ],
   [
    "Megumi.Shadow",
    "100532748201417"
   ],
   [
    "Megumi.ShadowSwarm",
    "72424828296871"
   ],
   [
    "Megumi.ShadowSwarm1",
    "77826020629176"
   ],
   [
    "Megumi.ShadowSwarm2",
    "124644660953423"
   ],
   [
    "Megumi.ShadowSwarmHit",
    "74539388000853"
   ],
   [
    "Megumi.ShadowSwarmRun",
    "75686211329107"
   ],
   [
    "Megumi.Ultimate",
    "74442134184452"
   ],
   [
    "Megumi.Melee.Melee1",
    "75337033003776"
   ],
   [
    "Megumi.Melee.Melee2",
    "138489871864252"
   ],
   [
    "Megumi.Melee.Melee3",
    "96185406489877"
   ],
   [
    "Megumi.Melee.Melee4",
    "105287938257399"
   ]
  ]
 },
 {
  "character": "Mahoraga",
  "anims": [
   [
    "Mahoraga.Adaptation",
    "139336998459583"
   ],
   [
    "Mahoraga.DivinePummel",
    "115683433001643"
   ],
   [
    "Mahoraga.Earthquake",
    "85024950165903"
   ],
   [
    "Mahoraga.GroundPitch",
    "138852224035589"
   ],
   [
    "Mahoraga.Parry",
    "103194057617238"
   ],
   [
    "Mahoraga.Takedown",
    "84870056161157"
   ],
   [
    "Mahoraga.WorldSlash",
    "135894053646223"
   ],
   [
    "Mahoraga.Melee.Melee1",
    "109718372214725"
   ],
   [
    "Mahoraga.Melee.Melee2",
    "121800365664070"
   ],
   [
    "Mahoraga.Melee.Melee3",
    "96513213736303"
   ],
   [
    "Mahoraga.Melee.Melee4",
    "79037514387169"
   ],
   [
    "Mahoraga.Melee.Up",
    "119434039452526"
   ],
   [
    "Mahoraga.Melee.Down",
    "114797198964940"
   ]
  ]
 },
 {
  "character": "Mahito",
  "anims": [
   [
    "Mahito.BodyRepel",
    "108319980293313"
   ],
   [
    "Mahito.CrushingRushdown",
    "89888040037257"
   ],
   [
    "Mahito.CrushingRushdownHit",
    "110351847187022"
   ],
   [
    "Mahito.DrillSplit",
    "128779949980528"
   ],
   [
    "Mahito.FaceBlitz",
    "105068005007692"
   ],
   [
    "Mahito.FocusStrike",
    "72475960800126"
   ],
   [
    "Mahito.ForceGrab",
    "72343192576784"
   ],
   [
    "Mahito.HeadSplitter",
    "86073608599582"
   ],
   [
    "Mahito.HeadSplitterHit",
    "88471344937304"
   ],
   [
    "Mahito.HeartPiercer",
    "94223344057046"
   ],
   [
    "Mahito.IdleTransfig",
    "123690534435200"
   ],
   [
    "Mahito.SelfPerfection",
    "75736902190737"
   ],
   [
    "Mahito.Soulfire",
    "89092734635186"
   ],
   [
    "Mahito.SpikeWrath",
    "127727754867974"
   ],
   [
    "Mahito.Stockpile",
    "103493656287292"
   ],
   [
    "Mahito.Ultimate",
    "80852442092385"
   ],
   [
    "Mahito.Ultimate2",
    "125455197945793"
   ],
   [
    "Mahito.WideStrike",
    "76313364850487"
   ],
   [
    "Mahito.WideStrikeHit",
    "80643664050281"
   ],
   [
    "Mahito.Variants.ChaseClub",
    "81786875517933"
   ],
   [
    "Mahito.Variants.ChaseSword",
    "134461702265323"
   ],
   [
    "Mahito.Variants.ChaseArmor",
    "130013701390383"
   ],
   [
    "Mahito.Melee.Melee1",
    "126277739156443"
   ],
   [
    "Mahito.Melee.Melee2",
    "99710481887795"
   ],
   [
    "Mahito.Melee.Melee3",
    "121322029260156"
   ],
   [
    "Mahito.Melee.Melee4",
    "122655618588472"
   ],
   [
    "Mahito.Melee.Up",
    "98845475810982"
   ],
   [
    "Mahito.Variants.MeleeClub.Melee1",
    "98365018553171"
   ],
   [
    "Mahito.Variants.MeleeClub.Melee2",
    "80150988150906"
   ],
   [
    "Mahito.Variants.MeleeClub.Melee3",
    "86918383671100"
   ],
   [
    "Mahito.Variants.MeleeClub.Melee4",
    "85887300265206"
   ],
   [
    "Mahito.Variants.MeleeClub.Down",
    "114562626498918"
   ],
   [
    "Mahito.Variants.MeleeSword.Melee1",
    "79568627671998"
   ],
   [
    "Mahito.Variants.MeleeSword.Melee2",
    "105870773841535"
   ],
   [
    "Mahito.Variants.MeleeSword.Melee3",
    "130659585624615"
   ],
   [
    "Mahito.Variants.MeleeSword.Melee4",
    "138626478088332"
   ]
  ]
 },
 {
  "character": "Choso",
  "anims": [
   [
    "Choso.BloodEdge",
    "100446064103831"
   ],
   [
    "Choso.BloodEdgeVictim",
    "99998493953272"
   ],
   [
    "Choso.BloodRain",
    "117371289990421"
   ],
   [
    "Choso.Convergence",
    "120319825505172"
   ],
   [
    "Choso.PiercingBlood",
    "127171275866632"
   ],
   [
    "Choso.PlasmaWave",
    "107067953428369"
   ],
   [
    "Choso.RedScale",
    "84039122607068"
   ],
   [
    "Choso.RedScaleAir",
    "87805684702890"
   ],
   [
    "Choso.RedScaleVictim",
    "129385939516650"
   ],
   [
    "Choso.SlicingExorcism",
    "114321791577837"
   ],
   [
    "Choso.Supernova",
    "85569553424083"
   ],
   [
    "Choso.SupernovaCounter",
    "117045209683198"
   ],
   [
    "Choso.Ultimate",
    "105826208784475"
   ],
   [
    "Choso.WingKing",
    "95097480425566"
   ],
   [
    "Choso.WingKingVictim",
    "113762948876108"
   ],
   [
    "Choso.Melee.Melee1",
    "96185406489877"
   ],
   [
    "Choso.Melee.Melee2",
    "105077924973072"
   ],
   [
    "Choso.Melee.Melee3",
    "119042572747325"
   ],
   [
    "Choso.Melee.Melee4",
    "105287938257399"
   ]
  ]
 },
 {
  "character": "Todo",
  "anims": [
   [
    "Todo.Brothers",
    "72828071138653"
   ],
   [
    "Todo.BruteForce",
    "136536827155962"
   ],
   [
    "Todo.ClimaxJump",
    "84448423136678"
   ],
   [
    "Todo.ClimaxJumpHit",
    "127715649911604"
   ],
   [
    "Todo.Dreams",
    "89677028738408"
   ],
   [
    "Todo.ElbowDrop",
    "115042679536959"
   ],
   [
    "Todo.IdolDebut",
    "121572833341748"
   ],
   [
    "Todo.PebbleThrow",
    "111720035828971"
   ],
   [
    "Todo.PebbleThrowHit",
    "71785780090087"
   ],
   [
    "Todo.SwiftKick",
    "84737448668938"
   ],
   [
    "Todo.SwiftKickHit",
    "124120330557927"
   ],
   [
    "Todo.Ultimate",
    "77323960817460"
   ],
   [
    "Todo.UltimateSummon",
    "84527203471730"
   ],
   [
    "Todo.TakadaJoint.JumpStart",
    "92313325989822"
   ],
   [
    "Todo.TakadaJoint.JumpEnd",
    "112868588878225"
   ],
   [
    "Todo.TakadaJoint.TakadaIdle",
    "102765720260431"
   ],
   [
    "Todo.TakadaJoint.Emote",
    "140557689031802"
   ],
   [
    "Todo.Clap.Clap1",
    "131358603583212"
   ],
   [
    "Todo.Clap.Clap2",
    "91074768993486"
   ],
   [
    "Todo.Clap.Clap3",
    "116040503139675"
   ],
   [
    "Todo.Melee.Melee1",
    "96327114254575"
   ],
   [
    "Todo.Melee.Melee2",
    "107029561762376"
   ],
   [
    "Todo.Melee.Melee3",
    "117831239064143"
   ],
   [
    "Todo.Melee.Melee4",
    "127851700400958"
   ]
  ]
 },
 {
  "character": "Locust",
  "anims": [
   [
    "Locust.BlackMucus",
    "129132347098646"
   ],
   [
    "Locust.BugFlight",
    "121550561336691"
   ],
   [
    "Locust.Flight",
    "115001703805775"
   ],
   [
    "Locust.FourArmed",
    "129678103897608"
   ],
   [
    "Locust.SnapChomp",
    "134777193523837"
   ],
   [
    "Locust.SnapChompHit",
    "94771523237279"
   ],
   [
    "Locust.Ultimate",
    "94590184881876"
   ],
   [
    "Locust.Melee.Melee1",
    "85068785050521"
   ],
   [
    "Locust.Melee.Melee2",
    "79086910454958"
   ],
   [
    "Locust.Melee.Melee3",
    "108027796023968"
   ],
   [
    "Locust.Melee.Melee4",
    "99205259396653"
   ]
  ]
 },
 {
  "character": "Hiromi",
  "anims": [
   [
    "Hiromi.DeadlySentence",
    "101617544363219"
   ],
   [
    "Hiromi.Execution",
    "132704398648016"
   ],
   [
    "Hiromi.ExecutionHit1",
    "132316713905598"
   ],
   [
    "Hiromi.ExecutionHit2",
    "75178683584164"
   ],
   [
    "Hiromi.ExecutionHit3",
    "99833231605480"
   ],
   [
    "Hiromi.ExtendSwing",
    "89652378115594"
   ],
   [
    "Hiromi.FinalJudgement",
    "106649604455931"
   ],
   [
    "Hiromi.FinalJudgementHit",
    "81597967165882"
   ],
   [
    "Hiromi.Grapple",
    "71186534081075"
   ],
   [
    "Hiromi.JusticeServed",
    "76519264603956"
   ],
   [
    "Hiromi.JusticeServedHit",
    "128557259779846"
   ],
   [
    "Hiromi.TwirlingStrikes",
    "124340599144108"
   ],
   [
    "Hiromi.Ultimate",
    "80922461169812"
   ],
   [
    "Hiromi.Dodge.Dodge1",
    "70593304937741"
   ],
   [
    "Hiromi.Dodge.Dodge2",
    "103513893010999"
   ],
   [
    "Hiromi.Dodge.Dodge3",
    "140381676724931"
   ],
   [
    "Hiromi.Dodge.Dodge4",
    "111214152450580"
   ],
   [
    "Hiromi.Dodge.Dodge5",
    "85003123457049"
   ],
   [
    "Hiromi.Verdict",
    "132754851925571"
   ],
   [
    "Hiromi.TripleSentence",
    "124243904748268"
   ],
   [
    "Hiromi.TripleSentenceHit",
    "100590912634893"
   ],
   [
    "Hiromi.JudgeReach",
    "124759375124281"
   ],
   [
    "Hiromi.JudgeReachHit",
    "131174893248941"
   ],
   [
    "Hiromi.JudgeReachHit2",
    "93847231892553"
   ],
   [
    "Hiromi.GavelThrow",
    "86362077638309"
   ],
   [
    "Hiromi.Melee.Melee1",
    "133936641185614"
   ],
   [
    "Hiromi.Melee.Melee2",
    "122573730331631"
   ],
   [
    "Hiromi.Melee.Melee3",
    "82400997593751"
   ],
   [
    "Hiromi.Melee.Melee4",
    "118634493886688"
   ],
   [
    "Hiromi.Melee2.Melee1",
    "139280948741186"
   ],
   [
    "Hiromi.Melee2.Melee2",
    "109340494549365"
   ],
   [
    "Hiromi.Melee2.Melee3",
    "98577624776161"
   ],
   [
    "Hiromi.Melee2.Melee4",
    "117831239064143"
   ],
   [
    "Hiromi.Melee2.Chase",
    "120951759618134"
   ],
   [
    "Hiromi.JudgeReach2",
    "133869529005453"
   ],
   [
    "Hiromi.PressingCharges",
    "135411487367370"
   ]
  ]
 },
 {
  "character": "Yuki",
  "anims": [
   [
    "Yuki.GarudaRebound",
    "115097960689033"
   ],
   [
    "Yuki.GarudaStab",
    "77833820443705"
   ],
   [
    "Yuki.GarudaStabHit",
    "100538903104836"
   ],
   [
    "Yuki.MassBreaker",
    "104793932628579"
   ],
   [
    "Yuki.RisingStar",
    "94347210073500"
   ],
   [
    "Yuki.Ultimate",
    "79717812541463"
   ],
   [
    "Yuki.MeleeOld.Melee1",
    "106474043944206"
   ],
   [
    "Yuki.MeleeOld.Melee2",
    "91990544700842"
   ],
   [
    "Yuki.MeleeOld.Melee3",
    "107825127494342"
   ],
   [
    "Yuki.MeleeOld.Melee4",
    "97504088532041"
   ],
   [
    "Yuki.Melee.Melee1",
    "131909724908049"
   ],
   [
    "Yuki.Melee.Melee2",
    "72575786212990"
   ],
   [
    "Yuki.Melee.Melee3",
    "119248903710146"
   ],
   [
    "Yuki.Melee.Melee4",
    "123168328205349"
   ]
  ]
 },
 {
  "character": "Heian",
  "anims": [
   [
    "Heian.Chant",
    "93265997037616"
   ],
   [
    "Heian.Cleave",
    "110906451704074"
   ],
   [
    "Heian.Dismantle",
    "131826588098422"
   ],
   [
    "Heian.FlameArrow",
    "70840150456007"
   ],
   [
    "Heian.Kamutoke",
    "137007125977081"
   ],
   [
    "Heian.MalevolentShrine",
    "73048386765082"
   ],
   [
    "Heian.WCS",
    "88215274584883"
   ]
  ]
 },
 {
  "character": "Yuta",
  "anims": [
   [
    "Yuta.ResoluteSlash",
    "89582140026963"
   ],
   [
    "Yuta.Revolve",
    "88911658010897"
   ],
   [
    "Yuta.SeveringPath",
    "104824728032437"
   ],
   [
    "Yuta.Sheath",
    "126213385043407"
   ],
   [
    "Yuta.Veilstep",
    "117178057848472"
   ],
   [
    "Yuta.VeilstepDive",
    "115432081398704"
   ],
   [
    "Yuta.SeveringPathAir",
    "140595869234331"
   ],
   [
    "Yuta.RevolveReaction",
    "139280845242450"
   ],
   [
    "Yuta.YutaBeam",
    "71783955283661"
   ],
   [
    "Yuta.Launch",
    "115912582567240"
   ],
   [
    "Yuta.Ultimate",
    "111952952886712"
   ],
   [
    "Yuta.JacobLadder",
    "73482562876920"
   ],
   [
    "Yuta.JacobLadderTarget",
    "76058065825374"
   ],
   [
    "Yuta.ElbowBeatdown",
    "93796567192197"
   ],
   [
    "Yuta.ElbowBeatdownTarget",
    "113432456707949"
   ],
   [
    "Yuta.RunSlash",
    "72914783159396"
   ],
   [
    "Yuta.CursedSpeech",
    "88005970155216"
   ],
   [
    "Yuta.Melee.Melee1",
    "133240987753043"
   ],
   [
    "Yuta.Melee.Melee2",
    "130806585141471"
   ],
   [
    "Yuta.Melee.Melee3",
    "131967150738931"
   ],
   [
    "Yuta.Melee.Melee4",
    "84442064935420"
   ],
   [
    "Yuta.Melee.Chase",
    "130135202362252"
   ],
   [
    "Yuta.Melee.Up",
    "73456086297777"
   ],
   [
    "Yuta.Melee.Down",
    "111750364977569"
   ],
   [
    "Yuta.SeveringSwing",
    "125904281673524"
   ],
   [
    "Yuta.Outburst",
    "95077220586856"
   ],
   [
    "Yuta.QuickdrawAerial",
    "109069266611522"
   ],
   [
    "Yuta.SecondWind",
    "108418554887656"
   ],
   [
    "Yuta.EnergyRipple",
    "131031842057158"
   ],
   [
    "Yuta.MeleeUlt.Melee1",
    "109432265703187"
   ],
   [
    "Yuta.MeleeUlt.Melee2",
    "137919635923292"
   ],
   [
    "Yuta.MeleeUlt.Melee3",
    "135256592475167"
   ],
   [
    "Yuta.MeleeUlt.Melee4",
    "121403322067812"
   ],
   [
    "Yuta.Ultimate2",
    "139556003259624"
   ],
   [
    "Yuta.SeveringPathSwordAir",
    "130834106305514"
   ],
   [
    "Yuta.LaunchGround",
    "129876493950288"
   ],
   [
    "Yuta.LaunchGroundMelee",
    "99942519870898"
   ],
   [
    "Yuta.RunPierce",
    "120355051037295"
   ]
  ]
 },
 {
  "character": "Charles",
  "anims": [
   [
    "Charles.Despair",
    "103013818601982"
   ],
   [
    "Charles.EyeCatch",
    "72933571933445"
   ],
   [
    "Charles.ShutUp",
    "79860101129549"
   ],
   [
    "Charles.ShutUpVictim",
    "116462971170564"
   ],
   [
    "Charles.Sacrilegious",
    "72932825817330"
   ],
   [
    "Charles.SacrilegiousHit",
    "93417504040395"
   ],
   [
    "Charles.Ultimate",
    "101956908324027"
   ],
   [
    "Charles.UltimateHit",
    "123476590646783"
   ],
   [
    "Charles.UltimateAfter",
    "98956365812665"
   ],
   [
    "Charles.Mark",
    "86313167610953"
   ],
   [
    "Charles.Melee.Melee1",
    "125689391910002"
   ],
   [
    "Charles.Melee.Melee2",
    "84080901810314"
   ],
   [
    "Charles.Melee.Melee3",
    "139833047658617"
   ],
   [
    "Charles.Melee.Melee4",
    "79271374075726"
   ],
   [
    "Charles.Melee.Up",
    "134243365075812"
   ]
  ]
 },
 {
  "character": "Mechamaru",
  "anims": [
   [
    "Mechamaru.BoostOnStart",
    "105934922038894"
   ],
   [
    "Mechamaru.BoostOnEnd",
    "76118979198026"
   ],
   [
    "Mechamaru.BoostOnTarget",
    "131158776477817"
   ],
   [
    "Mechamaru.UltraSpin",
    "120136894011461"
   ],
   [
    "Mechamaru.UltraSpinHit",
    "73306716731600"
   ],
   [
    "Mechamaru.UltraCannon",
    "93901924492394"
   ],
   [
    "Mechamaru.PuppetBarrage.User",
    "139105275342427"
   ],
   [
    "Mechamaru.PuppetBarrage.Grab",
    "73522808400163"
   ],
   [
    "Mechamaru.PuppetBarrage.Kick",
    "130123540243667"
   ],
   [
    "Mechamaru.Offloads.FunnyFall",
    "139595086016682"
   ],
   [
    "Mechamaru.Offloads.SmoothLanding1",
    "80744488373239"
   ],
   [
    "Mechamaru.Offloads.SmoothLanding2",
    "99249148382757"
   ],
   [
    "Mechamaru.Offloads.BackSlide",
    "119635500264882"
   ],
   [
    "Mechamaru.Offloads.SupermanLanding",
    "78540995456941"
   ],
   [
    "Mechamaru.Offloads.ArmsFlyIn",
    "91633722898431"
   ],
   [
    "Mechamaru.BoostOn",
    "87472283043607"
   ],
   [
    "Mechamaru.BoostOnHit",
    "131064175095241"
   ],
   [
    "Mechamaru.HeatEmission",
    "114277419400774"
   ],
   [
    "Mechamaru.MiracleCannon",
    "80465501985014"
   ],
   [
    "Mechamaru.PigeonViola",
    "89009042593684"
   ],
   [
    "Mechamaru.AbsoluteDestructionOLD",
    "99731350629462"
   ],
   [
    "Mechamaru.Absolute.GunShot",
    "118652212972529"
   ],
   [
    "Mechamaru.Absolute.Kick",
    "112445967418621"
   ],
   [
    "Mechamaru.Absolute.JumpCrouch",
    "84970451790939"
   ],
   [
    "Mechamaru.Absolute.Stagger",
    "134979023659909"
   ],
   [
    "Mechamaru.Absolute.Spawn",
    "89041939287063"
   ],
   [
    "Mechamaru.Absolute.UltEnd",
    "133460338652190"
   ],
   [
    "Mechamaru.Melee.Melee1",
    "98783064085844"
   ],
   [
    "Mechamaru.Melee.Melee2",
    "85148168523745"
   ],
   [
    "Mechamaru.Melee.Melee3",
    "108686045412945"
   ],
   [
    "Mechamaru.Melee.Melee4",
    "79718433989469"
   ],
   [
    "Mechamaru.Absolute.Melee.Melee1",
    "80504019426174"
   ],
   [
    "Mechamaru.Absolute.Melee.Melee2",
    "100835844904897"
   ],
   [
    "Mechamaru.Absolute.Melee.Melee3",
    "101862938993177"
   ],
   [
    "Mechamaru.Absolute.Melee.Melee4",
    "100919783371339"
   ],
   [
    "Mechamaru.Absolute.Melee.Up",
    "134243365075812"
   ],
   [
    "Mechamaru.AbsoluteDestruction",
    "137638103122538"
   ],
   [
    "Mechamaru.AbsoluteDestructionAir",
    "121239701968766"
   ]
  ]
 },
 {
  "character": "Naoya",
  "anims": [
   [
    "Naoya.Bleedout",
    "118607369830566"
   ],
   [
    "Naoya.BleedoutHit",
    "118284338553929"
   ],
   [
    "Naoya.CursoryImpact",
    "119211164876773"
   ],
   [
    "Naoya.DecisiveStrike",
    "86045680364061"
   ],
   [
    "Naoya.DecisiveStrikeHit",
    "70383415079592"
   ],
   [
    "Naoya.Flicker",
    "122607727974119"
   ],
   [
    "Naoya.ProjectionBreaker",
    "101079657277587"
   ],
   [
    "Naoya.Ultimate",
    "94616006376147"
   ],
   [
    "Naoya.UltimateHit",
    "115816549559515"
   ],
   [
    "Naoya.TopSpeed",
    "70890372338556"
   ],
   [
    "Naoya.FlashFreezing",
    "115589615022077"
   ],
   [
    "Naoya.TendrilGrab",
    "82149987460883"
   ],
   [
    "Naoya.MoonPalace",
    "115561023870463"
   ],
   [
    "Naoya.Acceleration",
    "129944486689528"
   ],
   [
    "Naoya.Melee.Melee1",
    "101283990868172"
   ],
   [
    "Naoya.Melee.Melee2",
    "108708446862011"
   ],
   [
    "Naoya.Melee.Melee3",
    "77583711129628"
   ],
   [
    "Naoya.Melee.Melee4",
    "116910683335467"
   ],
   [
    "Naoya.Melee2.Melee1",
    "77284264481284"
   ],
   [
    "Naoya.Melee2.Melee2",
    "108376755316792"
   ],
   [
    "Naoya.Melee2.Melee3",
    "74580112757879"
   ],
   [
    "Naoya.Melee2.Melee4",
    "101107501526373"
   ]
  ]
 },
 {
  "character": "Nanami",
  "anims": [
   [
    "Nanami.CleavingWhirlwind",
    "81210313723714"
   ],
   [
    "Nanami.SeveranceKick",
    "130957217409359"
   ],
   [
    "Nanami.BluntCut",
    "100811576955331"
   ],
   [
    "Nanami.Stabilize",
    "113359849246757"
   ],
   [
    "Nanami.StabilizeTarget",
    "139138600357187"
   ],
   [
    "Nanami.StabilizeTargetShort",
    "100525306083424"
   ],
   [
    "Nanami.RatioBreaker.RatioBreak1",
    "78578012001859"
   ],
   [
    "Nanami.RatioBreaker.RatioBreak2",
    "137451357351000"
   ],
   [
    "Nanami.RatioBreaker.RatioBreak3",
    "86618245908620"
   ],
   [
    "Nanami.RatioBreaker.RatioBreak4",
    "131948591638044"
   ],
   [
    "Nanami.RatioBreakStun",
    "125307894046906"
   ],
   [
    "Nanami.Ultimate",
    "108695775669287"
   ],
   [
    "Nanami.Melee.Melee1",
    "84359513001979"
   ],
   [
    "Nanami.Melee.Melee2",
    "79436586236026"
   ],
   [
    "Nanami.Melee.Melee3",
    "102285403332509"
   ],
   [
    "Nanami.Melee.Melee4",
    "104137631480391"
   ],
   [
    "Nanami.Melee.Up",
    "78540777177847"
   ],
   [
    "Nanami.Melee.Down",
    "92966188946988"
   ],
   [
    "Nanami.MeleeUlt.Melee1",
    "114913455544468"
   ],
   [
    "Nanami.MeleeUlt.Melee2",
    "84602523265622"
   ],
   [
    "Nanami.MeleeUlt.Melee3",
    "102085681670810"
   ],
   [
    "Nanami.MeleeUlt.Melee4",
    "115446267797335"
   ],
   [
    "Nanami.Sharpen",
    "134622628645994"
   ],
   [
    "Nanami.Interrogate",
    "89891294371787"
   ],
   [
    "Nanami.InterrogateHit",
    "71077954560899"
   ],
   [
    "Nanami.InterrogateFinalHit",
    "112843155753457"
   ],
   [
    "Nanami.Collapse",
    "122015481201264"
   ]
  ]
 },
 {
  "character": "Goku",
  "anims": [
   [
    "Goku.Kamehameha",
    "81971779090581"
   ],
   [
    "Goku.KiSpam",
    "128537969081721"
   ],
   [
    "Goku.StaffExtend",
    "87481059409847"
   ],
   [
    "Goku.StaffUppercut",
    "117318845383884"
   ],
   [
    "Goku.Ultimate",
    "136161556678024"
   ],
   [
    "Goku.Melee.Melee1",
    "104087365067491"
   ],
   [
    "Goku.Melee.Melee2",
    "97215638330770"
   ],
   [
    "Goku.Melee.Melee3",
    "100474683542881"
   ],
   [
    "Goku.Melee.Melee4",
    "131279921755936"
   ]
  ]
 },
 {
  "character": "Haruta",
  "anims": [
   [
    "Haruta.Ambush",
    "120914276661831"
   ],
   [
    "Haruta.Stinger",
    "95494223368246"
   ],
   [
    "Haruta.Backstab",
    "133303451091615"
   ],
   [
    "Haruta.BackstabTargetBack",
    "134821755643646"
   ],
   [
    "Haruta.BackstabTargetFront",
    "82281135644263"
   ],
   [
    "Haruta.Trip",
    "102053631728986"
   ],
   [
    "Haruta.CheapShot",
    "76957377224584"
   ],
   [
    "Haruta.DirtyPlay",
    "108865650924154"
   ],
   [
    "Haruta.Hand.JawbreakerHit",
    "94150970896972"
   ],
   [
    "Haruta.Hand.JawbreakerVictim",
    "119918873304328"
   ],
   [
    "Haruta.Melee.Melee1",
    "133447840605824"
   ],
   [
    "Haruta.Melee.Melee2",
    "113963875117859"
   ],
   [
    "Haruta.Melee.Melee3",
    "106282708121342"
   ],
   [
    "Haruta.Melee.Melee4",
    "101681158700275"
   ],
   [
    "Haruta.Melee.Melee4Victim",
    "112976111828157"
   ],
   [
    "Haruta.Melee.MeleeChase",
    "122074769949629"
   ],
   [
    "Haruta.Melee.SwordChase",
    "134917827147266"
   ],
   [
    "Haruta.Melee.Up",
    "119152716475706"
   ],
   [
    "Haruta.Melee.Down",
    "100040983719699"
   ],
   [
    "Haruta.Taunt1",
    "87559130748823"
   ],
   [
    "Haruta.Taunt2",
    "138967793150950"
   ],
   [
    "Haruta.Taunt3",
    "78196072237542"
   ],
   [
    "Haruta.Taunt4",
    "138760573388652"
   ]
  ]
 },
 {
  "character": "MeiMei",
  "anims": [
   [
    "MeiMei.BirdCall",
    "99180695169591"
   ],
   [
    "MeiMei.BirdHold",
    "117836779292116"
   ],
   [
    "MeiMei.Bounding",
    "139956651661073"
   ],
   [
    "MeiMei.BoundingVictim",
    "135327783612081"
   ],
   [
    "MeiMei.Circling",
    "90781290293652"
   ],
   [
    "MeiMei.CirclingVictim",
    "114723941013668"
   ],
   [
    "MeiMei.CirclingVictimFinisher",
    "89368678158919"
   ],
   [
    "MeiMei.Flock",
    "96397814657727"
   ],
   [
    "MeiMei.GlidingFlight",
    "72157009600725"
   ],
   [
    "MeiMei.GlidingFlightVictim",
    "85759204747311"
   ],
   [
    "MeiMei.ImpetusUpdraft",
    "92081142332466"
   ],
   [
    "MeiMei.Melee.Melee1",
    "114985590391235"
   ],
   [
    "MeiMei.Melee.Melee2",
    "108449614447004"
   ],
   [
    "MeiMei.Melee.Melee3",
    "122170399962557"
   ],
   [
    "MeiMei.Melee.Melee4",
    "117638619792450"
   ],
   [
    "MeiMei.Melee.Up",
    "136978371933277"
   ],
   [
    "MeiMei.Melee.Down",
    "87792276744794"
   ],
   [
    "MeiMei.Melee.Chase",
    "128267680345523"
   ],
   [
    "MeiMei.ImpetusNew",
    "126362899488198"
   ],
   [
    "MeiMei.Murmurate",
    "81007905598407"
   ],
   [
    "MeiMei.Teleport",
    "93433910019592"
   ],
   [
    "MeiMei.Ultimate",
    "130209038947701"
   ]
  ]
 },
 {
  "character": "Hanami",
  "anims": [
   [
    "Hanami.BudShot",
    "96466374346823"
   ],
   [
    "Hanami.DefenseResponse",
    "81953935260783"
   ],
   [
    "Hanami.FlowerField",
    "102221764735089"
   ],
   [
    "Hanami.RootSwarm",
    "113722638806911"
   ],
   [
    "Hanami.SurgingThorns",
    "92595499555055"
   ],
   [
    "Hanami.Melee.Melee1",
    "111083699259354"
   ],
   [
    "Hanami.Melee.Melee2",
    "88849926869776"
   ],
   [
    "Hanami.Melee.Melee3",
    "89537672683114"
   ],
   [
    "Hanami.Melee.Melee4",
    "109598602517674"
   ],
   [
    "Hanami.Melee.Chase",
    "138169151223960"
   ],
   [
    "Hanami.MeleeUlt.Melee1",
    "115781423162319"
   ],
   [
    "Hanami.MeleeUlt.Melee2",
    "106245594701442"
   ],
   [
    "Hanami.MeleeUlt.Melee3",
    "139925289573265"
   ],
   [
    "Hanami.MeleeUlt.Melee4",
    "128437228548370"
   ],
   [
    "Hanami.Empower",
    "87128908378141"
   ],
   [
    "Hanami.Ultimate",
    "84712031901002"
   ],
   [
    "Hanami.Domain",
    "105801749091005"
   ],
   [
    "Hanami.CursedBuds",
    "100108404823407"
   ],
   [
    "Hanami.Beam",
    "131904892480473"
   ]
  ]
 },
 {
  "character": "Ryu",
  "anims": [
   [
    "Ryu.Appetizer",
    "70394890117813"
   ],
   [
    "Ryu.GraniteBlast",
    "73243807139765"
   ],
   [
    "Ryu.HadNoIdea",
    "99818212174021"
   ],
   [
    "Ryu.HadNoIdeaHit",
    "80896689369384"
   ],
   [
    "Ryu.Recovery",
    "135300554211825"
   ],
   [
    "Ryu.Recovery2",
    "135915491872296"
   ],
   [
    "Ryu.SecondHelping",
    "138826705245289"
   ],
   [
    "Ryu.ThisDessert",
    "131917532383382"
   ],
   [
    "Ryu.ThisDessertHit",
    "86743305257266"
   ],
   [
    "Ryu.Ultimate",
    "113479860283691"
   ],
   [
    "Ryu.Unsatisfied",
    "114822879878184"
   ],
   [
    "Ryu.WhatAreYouAfter",
    "86568794583359"
   ],
   [
    "Ryu.WhatAreYouAfterHit",
    "110163656525929"
   ],
   [
    "Ryu.Melee.Chase",
    "83782195794718"
   ],
   [
    "Ryu.Melee.Melee3_2",
    "92698956945928"
   ],
   [
    "Ryu.WerentInvited",
    "86463226245064"
   ],
   [
    "Ryu.Recovery3",
    "91450617822876"
   ]
  ]
 },
 {
  "character": "Kurourushi",
  "anims": [
   [
    "Kurourushi.FesteringStrikes",
    "83430571986421"
   ],
   [
    "Kurourushi.Detach",
    "78636717376287"
   ],
   [
    "Kurourushi.Reattach",
    "104082985552315"
   ],
   [
    "Kurourushi.ChokeholdHit",
    "90695654160865"
   ],
   [
    "Kurourushi.ChokeholdVictim",
    "137890465172565"
   ],
   [
    "Kurourushi.EarthenTrance",
    "93751660565233"
   ],
   [
    "Kurourushi.RoachSwarm",
    "116119661056362"
   ],
   [
    "Kurourushi.Melee.Melee1",
    "105961366724096"
   ],
   [
    "Kurourushi.Melee.Melee2",
    "86519781516542"
   ],
   [
    "Kurourushi.Melee.Melee3",
    "123591522021548"
   ],
   [
    "Kurourushi.Melee.Melee4",
    "124726819047447"
   ],
   [
    "Kurourushi.MeleeDetach.Melee1",
    "93880529089759"
   ],
   [
    "Kurourushi.MeleeDetach.Melee2",
    "131033861605339"
   ],
   [
    "Kurourushi.MeleeDetach.Melee3",
    "118433412162663"
   ],
   [
    "Kurourushi.MeleeDetach.Melee4",
    "110425977429691"
   ],
   [
    "Kurourushi.Parthenogenesis",
    "94093535314017"
   ],
   [
    "Kurourushi.Eat",
    "104597702149205"
   ],
   [
    "Kurourushi.EatVictim",
    "95145258027958"
   ],
   [
    "Kurourushi.Melee.Down",
    "136466703751033"
   ]
  ]
 },
 {
  "character": "Reggie",
  "anims": [
   [
    "Reggie.GushingWound",
    "106478217686775"
   ],
   [
    "Reggie.Homerun",
    "80552926761100"
   ],
   [
    "Reggie.Littering",
    "132615896981226"
   ],
   [
    "Reggie.Coupon",
    "77161050579175"
   ],
   [
    "Reggie.PianoDrop",
    "86293749971049"
   ],
   [
    "Reggie.GarageSale",
    "108407413391495"
   ],
   [
    "Reggie.BluntTrauma",
    "103659500760745"
   ],
   [
    "Reggie.BluntTraumaHit",
    "118544637360490"
   ],
   [
    "Reggie.Discard",
    "100515557795491"
   ],
   [
    "Reggie.Melee.Melee1",
    "106892235857467"
   ],
   [
    "Reggie.Melee.Melee2",
    "93623649598782"
   ],
   [
    "Reggie.Melee.Melee3",
    "128057999506702"
   ],
   [
    "Reggie.Melee.Melee4",
    "76372421343979"
   ],
   [
    "Reggie.Drone.DroneStrikeStart",
    "70619893542373"
   ],
   [
    "Reggie.PoleVault",
    "72249315151281"
   ],
   [
    "Reggie.Fleche",
    "84063127664904"
   ],
   [
    "Reggie.SpeedCrash",
    "133042937840159"
   ],
   [
    "Reggie.SpeedCrashHit",
    "114604121055247"
   ]
  ]
 },
 {
  "character": "Uro",
  "anims": [
   [
    "Uro.Melee.Melee1",
    "107852433150124"
   ],
   [
    "Uro.Melee.Melee2",
    "80809423999548"
   ],
   [
    "Uro.Melee.Melee3",
    "135805825263494"
   ],
   [
    "Uro.Melee.Melee4",
    "110958607174992"
   ],
   [
    "Uro.BlindRage",
    "84784070267976"
   ],
   [
    "Uro.BlindRageHit",
    "80563719529224"
   ],
   [
    "Uro.ThinIceBreaker",
    "127457641316758"
   ],
   [
    "Uro.ThinIceBreaker2",
    "71262912144187"
   ],
   [
    "Uro.SkyDistortion",
    "105191773344078"
   ],
   [
    "Uro.Ultimate",
    "124099249547203"
   ],
   [
    "Uro.Melee.Chase",
    "106224500692893"
   ]
  ]
 }
];
