// The icons the app uses (Lucide), by the names core/schema.js gives node
// kinds and categories, plus the UI's own. Add an import and an entry to use
// another; tree-shaking keeps the rest out of the bundle.
import {
  ArrowDown,
  ArrowUp,
  Bomb,
  BookOpen,
  Box,
  Camera,
  Check,
  ChevronsLeft,
  ChevronsRight,
  Clock,
  Copy,
  Crosshair,
  Download,
  Eye,
  FilePlus2,
  FileText,
  Footprints,
  Hand,
  Hash,
  Info,
  Link,
  LocateFixed,
  Maximize2,
  Minimize2,
  Moon,
  Navigation,
  Pause,
  PersonStanding,
  Play,
  Plus,
  Redo2,
  Repeat,
  Save,
  Search,
  Send,
  Shield,
  ShieldCheck,
  SkipBack,
  Sparkles,
  Split,
  StepBack,
  StepForward,
  Sun,
  Swords,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  UserRound,
  Volume2,
  VolumeX,
  X,
  Zap,
  FolderOpen,
  ChevronDown,
  ChevronRight,
  Minus,
  List,
  SlidersHorizontal,
  SkipForward,
  MousePointer2,
  Brush,
  Eraser,
  Shapes,
  Type,
  BatteryMedium,
  CircleDot,
  Languages,
  Square,
  Circle,
  Triangle,
  Diamond,
  ImagePlus,
  Image,
  Layers,
  Frame,
  EyeOff,
  ArrowRight,
  ArrowLeft,
  MoveHorizontal,
  MoveVertical,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  FileArchive,
  Sword,
  Wind,
  Percent,
  Scissors,
  Radio,
  Film,
  Command,
  Bot,
  Plug,
  CircleHelp,
  Keyboard,
  LogOut,
  Clipboard,
  ClipboardPaste,
  Star,
  History,
  Settings,
  Video,
  MessageSquare,
  KeyRound,
  ExternalLink,
  Wand2,
  Route,
  Aperture,
  LayoutGrid,
  Pencil,
  RefreshCw,
  Loader2,
  CircleStop,
  Move,
  Scale3d,
  Rotate3d,
  Globe,
  Spline,
  ChartSpline,
  CopyPlus,
  ImageUp,
} from 'lucide-preact';

const ICONS = {
  'pointer': MousePointer2,
  'brush': Brush,
  'eraser': Eraser,
  'shapes': Shapes,
  'type': Type,
  'battery': BatteryMedium,
  'battery-medium': BatteryMedium,
  'circle-dot': CircleDot,
  'languages': Languages,
  'square': Square,
  'circle': Circle,
  'triangle': Triangle,
  'diamond': Diamond,
  'image-plus': ImagePlus,
  'image': Image,
  'layers': Layers,
  'frame': Frame,
  'eye-off': EyeOff,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  'rotate-cw': RotateCw,
  'rotate-ccw': RotateCcw,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'file-archive': FileArchive,
  'sword': Sword,
  'wind': Wind,
  'percent': Percent,
  'scissors': Scissors,
  'radio': Radio,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  minus: Minus,
  list: List,
  sliders: SlidersHorizontal,
  'skip-forward': SkipForward,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  bomb: Bomb,
  book: BookOpen,
  box: Box,
  camera: Camera,
  check: Check,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  clock: Clock,
  copy: Copy,
  crosshair: Crosshair,
  download: Download,
  eye: Eye,
  'file-plus': FilePlus2,
  'file-text': FileText,
  folder: FolderOpen,
  footprints: Footprints,
  hand: Hand,
  hash: Hash,
  info: Info,
  link: Link,
  'locate-fixed': LocateFixed,
  moon: Moon,
  navigation: Navigation,
  pause: Pause,
  'person-standing': PersonStanding,
  play: Play,
  plus: Plus,
  redo: Redo2,
  repeat: Repeat,
  save: Save,
  search: Search,
  send: Send,
  shield: Shield,
  'shield-check': ShieldCheck,
  'skip-back': SkipBack,
  sparkles: Sparkles,
  split: Split,
  'step-back': StepBack,
  'step-forward': StepForward,
  sun: Sun,
  swords: Swords,
  timer: Timer,
  'trash-2': Trash2,
  warning: TriangleAlert,
  undo: Undo2,
  upload: Upload,
  'user-round': UserRound,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  x: X,
  'maximize-2': Maximize2,
  'minimize-2': Minimize2,
  zap: Zap,
  'film': Film,
  'command': Command,
  'bot': Bot,
  'plug': Plug,
  'help': CircleHelp,
  'keyboard': Keyboard,
  'log-out': LogOut,
  'clipboard': Clipboard,
  'paste': ClipboardPaste,
  'star': Star,
  'history': History,
  'settings': Settings,
  'video': Video,
  'message': MessageSquare,
  'key': KeyRound,
  'external-link': ExternalLink,
  'wand': Wand2,
  'route': Route,
  'aperture': Aperture,
  'layout': LayoutGrid,
  'pencil': Pencil,
  'refresh': RefreshCw,
  'loader': Loader2,
  'circle-stop': CircleStop,
  'move': Move,
  'scale': Scale3d,
  'rotate': Rotate3d,
  'globe': Globe,
  'mouse-pointer': MousePointer2,
  'spline': Spline,
  'graph': ChartSpline,
  'copy-plus': CopyPlus,
  'image-up': ImageUp,
};

export function Icon({ name, size = 16, class: className, ...rest }) {
  const Glyph = ICONS[name] ?? Info;
  return <Glyph size={size} strokeWidth={1.75} class={`icon ${className ?? ''}`} aria-hidden="true" {...rest} />;
}
